apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: detector-monitor
  namespace: spy-options-bot
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: detector
  endpoints:
  - port: metrics
    interval: 15s
