apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: spy-options-bot
data:
    fluent.conf: |
      <source>
        @type tail
        path /var/log/containers/*.log
        pos_file /tmp/fluentd-containers.log.pos
        tag kubernetes.*
        read_from_head true
        <parse>
          @type cri
        </parse>
      </source>

      <filter kubernetes.**>
        @type kubernetes_metadata
      </filter>

      <filter kubernetes.**>
        @type grep
        <regexp>
          key $.kubernetes.namespace_name
          pattern ^spy-options-bot$
        </regexp>
      </filter>

      <match kubernetes.**>
        @type azure-loganalytics
        customer_id "#{ENV['WORKSPACE_ID']}"
        shared_key "#{ENV['SHARED_KEY']}"
        log_type SpyOptionsPlatform
      </match>
    
    
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: spy-options-bot
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccountName: fluentd
      imagePullSecrets:
      - name: acr-secret
      securityContext:
        runAsUser: 0
      containers:
      - name: fluentd
        image: acrspyoptions.azurecr.io/spy-fluentd:v1.0
        env:
        - name: FLUENT_UID
          value: "0"
        - name: WORKSPACE_ID
          valueFrom:
            secretKeyRef:
              name: fluentd-azure-credentials
              key: workspace_id
        - name: SHARED_KEY
          valueFrom:
            secretKeyRef:
              name: fluentd-azure-credentials
              key: shared_key
        volumeMounts:
        - name: config
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
        - name: varlog
          mountPath: /var/log
        - name: containers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: fluentd-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: containers
        hostPath:
          path: /var/log/pods
          
     
